app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log in')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from app.model import users

login_manager = LoginManager()
login_manager.login_view = 'main.login'
bootstrap = Bootstrap()

@login_manager.user_loader
def load_user(user_id):
    for user in users:
        if user.get_id() == user_id:
            return user
    return None

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'You will never guess'
    login_manager.init_app(app)
    bootstrap.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import redirect, render_template, url_for
from flask_login import login_required, login_user, logout_user
from app.main import bp
from app.main.forms import LoginForm
from app.model import users

@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/redirect')
def do_redirect():
    return redirect(url_for('main.index'))

@bp.route('/restricted')
@login_required
def restricted():
    return render_template('restricted.html')

@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        for user in users:
            if user.username == username:
                login_user(user)
                return redirect(url_for('main.restricted'))
        return "Login failed"
    return render_template('login.html', form=form)

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return render_template('logout.html')

app/templates/index.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
This page is public.
<ul>
<li><a href="{{ url_for('main.restricted') }}">Restricted</a></li>
{% if not current_user.is_authenticated %}
<li><a href="{{ url_for('main.login') }}">Login</a></li>
{% endif %}
</ul>
{% endblock %}

app/templates/login.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/logout.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
You have been logged out.
<ul>
<li><a href="{{ url_for('main.restricted') }}">Restricted</a></li>
<li><a href="{{ url_for('main.login')}}">Login again</a></li>
</ul>
{% endblock %}

app/templates/restricted.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
This page is only visible to logged in users.
<ul>
<li><a href="{{ url_for('main.index')}}">Public</a></li>
<li><a href="{{ url_for('main.logout')}}">Logout</a></li>
</ul>
{% endblock %}